### ISSUE TITLE
filter resources according to date or time

### ISSUE THREAD

**Issue by Sedat1982** [bupaverse/edeaR#10]
Hello, in the below, i can filter the eventlog according to the resource names.  but, what if i want to filter the process time of resources according to the their process times.? for example, how can i add filter in this below code if i want to filter the resources according to the their process time( the resources which spend more than 5 hours for an acitivity)? i searched long time but couldnt find the solution. thanks

patients %>% filter_resource(c("r1","r2","r3")) %>% 
  processing_time("resource", units="hours") %>%
  plot()

**Comment by gertjanssenswillen** [comment]
You can "append" the information of the processing_time to the event log by setting the argument "append = TRUE".  

For example, the following gives information on the processing time of resource-activity combinations. 

```{r}
patients %>% processing_time("resource-activity")
# A tibble: 7 x 11
# Groups:   employee [7]
  employee handling                 min     q1   mean median    q3   max st_dev    iqr total
  <fct>    <fct>                  <dbl>  <dbl>  <dbl>  <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl>
1 r1       Registration          0.0345 0.0863 0.115  0.113  0.142 0.235 0.0397 0.0555  57.4
2 r2       Triage and Assessment 0.245  0.473  0.546  0.556  0.626 0.783 0.115  0.153  273. 
3 r3       Blood test            0      0      0.109  0      0.224 0.339 0.119  0.224   54.7
4 r4       MRI SCAN              0      0      0.0816 0      0.167 0.247 0.0889 0.167   40.8
5 r5       X-Ray                 0      0      0.105  0.114  0.202 0.340 0.108  0.202   52.7
6 r6       Discuss Results       0      0.0958 0.115  0.115  0.134 0.189 0.0285 0.0380  57.3
7 r7       Check-out             0      0.0655 0.0846 0.0861 0.102 0.162 0.0278 0.0368  42.3

```
The column "total" contains the total amount of time a resource has spend on an activity type. You can append this to the event log as follows

```
patients %>% processing_time("resource-activity", append = T, append_column = "total")
```
I.e. you state append = T, and which column to take. You can chose an of the output above. 

Now, you can use that column in a regular filter. However, I suggest to change the default name for simplicity. 

```
patients %>% processing_time("resource-activity", append = T, append_column = "total") -> patients
patients %>% dplyr::rename("proc_time" = "total_resource-activity_processing_time") -> patients
```
For example, al resources/activity combinations with a total time of more than 50. 

```
 patients %>% filter(proc_time > 50) %>% resources
# A tibble: 5 x 3
  employee absolute_frequency relative_frequency
  <fct>                 <int>              <dbl>
1 r1                      500              0.251
2 r2                      500              0.251
3 r6                      495              0.248
4 r5                      261              0.131
5 r3                      237              0.119
```

Hope this answers your questions? You can use the append for any edeaR-metric and at all granularity  levels, except for trace (at the moment). Depending on the output of the metric, you can chose which column you want to add to the event log. This provide an easy way to enrich your data with metrics, or to use them for filtering - further than the existing edeaR filters.

**Comment by Sedat1982** [comment]
Hello, Gert thanks for your helpful and detailed answer. i will use this method in my work. but how did you find the default column "total_resource-activity_processing_time"? the coloumn name was "total". and how can i find the default names of colums for others(min, mean, medan, max).?

**Comment by gertjanssenswillen** [comment]
In general it will be [column]_[level]_[metric]
In this case
column = total > the column that was chosen
level = resource-activity
metric = processing_time

At the moment I can't guarantee that this construction is always followed, but let's say in 99% it will be this. (Internally, there is a single function that creates this name, but it can be tweaked). It would probably by a good idea to request a name of the user instead of a default name.
