### ISSUE TITLE
filter_precedence "eventually_follows" doesn't seem to work

### ISSUE THREAD

**Issue by madsamjp** [bupaverse/edeaR#12]
Traces from 
`patients %>% traces`

1 Registration,Triage and Assessment,X-Ray,Discuss Results,Check-out                              258              0.516
2 Registration,Triage and Assessment,Blood test,MRI SCAN,Discuss Results,Check-out                234              0.468
3 Registration,Triage and Assessment,Blood test,MRI SCAN,Discuss Results                            2              0.004
4 Registration,Triage and Assessment,X-Ray                                                          2              0.004
5 Registration,Triage and Assessment                                                                2              0.004
6 Registration,Triage and Assessment,X-Ray,Discuss Results                                          1              0.002
7 Registration,Triage and Assessment,Blood test                                                     1              0.002

When I try to filter all traces that start from "Triage and Assessment" and eventually follow to "Discuss Results" I get none. Whereas the table above shows row 1, 2, 3, 6 are traces where this rule applies.

`patients %>%
      filter_precedence(antecedents = "Triage and Assessment",
                        consequents = "Discuss Results",
                        precedence_type = "eventually_follows",
                        filter_method = "all") %>%
  traces()`

This should give 4 traces, instead it gives 0.

"directly_follows" works fine (e.g. 
`patients %>%
  filter_precedence(antecedents = "Triage and Assessment",
                    consequents = "X-Ray",
                    precedence_type = "directly_follows",
                    filter_method = "all") %>%
  traces()`

**Comment by gertjanssenswillen** [comment]
This isssue in the current release of edeaR is known to us, and has been solved on github already. Installing the package from github should solve the problem. 

devtools::install_github("bupaverse/edear")
