### ISSUE TITLE
processing time column duplication issue

### ISSUE THREAD

**Issue by proyaschet** [bupaverse/edeaR#13]
Hi,

I tried to filter data using processing time but was getting column duplication issues and the same thing for obtaining processing time for event log. I have used example-log1,csv provided in the github repo of bupaR 

# please find sample code below
`example_log_1<-read.csv("example_log_1.csv")

example_log_1$timestamp <- as.POSIXct(example_log_1$timestamp)

example_log_1  %>% #a data.frame with the information in the table above
  eventlog(
    case_id = "patient",
    activity_id = "activity",
    activity_instance_id = "activity_instance",
    lifecycle_id = "status",
    timestamp = "timestamp",
    resource_id = "resource"
  ) -> example_log_1
example_log_1 %>% processing_time("log") %>% plot()`

# Please find the error below
`
Error: Column names `patient`, `activity`, and `resource` must not be duplicated.
Run `rlang::last_error()` to see where the error occurred.
`

### R Version
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

### bupar Version
bupaR_0.4.3
edeaR_0.8.4

Thanks and Regards,
Amar

**Comment by dupadhyaya** [comment]
even I have the same issue.. it is due latest update on dplyr which have to be incorporated in the library
![image](https://user-images.githubusercontent.com/6006907/84504724-0da53400-acda-11ea-8c7f-3a8a68e9c1da.png)
patients %>% processing_time(level='activity', unit='mins')
Error: Column names `patient`, `handling`, and `employee` must not be duplicated.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
The `add` argument of `group_by()` is deprecated as of dplyr 1.0.0.
Please use the `.add` argument instead.

**Comment by proyaschet** [comment]
Hi @dupadhyaya  do you have any workaround or fix for this

**Comment by gertjanssenswillen** [comment]
We are working on dplyr compatibility. Please install both edeaR and bupaR from github to see if the issues remain.

**Comment by dupadhyaya** [comment]
@proyaschet  as suggested reinstall edeaR and bupaR from git. It will work
@gertjanssenswillen :  Thank you. there may be other issues due to latest dplyr. Will update if I come across them. 
![image](https://user-images.githubusercontent.com/6006907/84516695-c758d080-aceb-11ea-90ae-b529d16ca087.png)
>#devtools::install_github('https://github.com/bupaverse/bupaR')
> #devtools::install_github('https://github.com/bupaverse/edeaR')
> patients %>% processing_time(level='activity', unit='mins')
# A tibble: 7 x 11
  handling           min    q1  mean median    q3   max st_dev   iqr  total relative_frequen~
  <fct>            <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl>  <dbl> <dbl>  <dbl>             <dbl>
1 Registration      49.7 124.   165.   163.  204.  338.   57.2  79.9 8.26e4            0.184

**Comment by dupadhyaya** [comment]
![image](https://user-images.githubusercontent.com/6006907/84530356-a0f16000-ad00-11ea-90ef-71eba6ef2f5c.png)
> patients %>% start_activities(level ='resource')
Error: **arrange() failed at implicit mutate() step.** 
x Could not create a temporary column for `..1`.
i `..1` is `handling`.
Run `rlang::last_error()` to see where the error occurred.

**Comment by gertjanssenswillen** [comment]
Thx, also fixed by #15

**Comment by proyaschet** [comment]
Thank you @dupadhyaya  @gertjanssenswillen issue is resolved.
