### ISSUE TITLE
filter all cases limited to first n steps

### ISSUE THREAD

**Issue by ChristelSwift** [bupaverse/edeaR#17]
would it be possible to add a filter that would limit the analysis (e.g. process map) to the first n steps?  i can see there are already filters for the first n cases but it would be great to be able to consider all cases filtered on their start of the process only for example.  
many thanks

**Comment by gertjanssenswillen** [comment]
Hi Christel. This can be done as follows (for example n = 5): 

```
data %>%
  group_by_case() %>%
  first_n(n = 5) %>%
  ungroup_eventlog()
```

first_n takes the first n activity instances (by time (!), not by position in the data)
group_by_case, you can do this for each case separately. After, you have to make sure to remove the grouping.

Please make sure that grouping_by_case() is still wat experimental. It is mainly intended for preprocessing data, as in this case, not in combination with analysis (where it is bound to create problems).

Best, 
Gert
