### ISSUE TITLE
end_activities

### ISSUE THREAD

**Issue by ghost** [bupaverse/edeaR#18]
Good day, 

I encounter some problems with the end_activities() function. The start_activities() function works without any problems but when I run the end_activities() function on the eventlog I always get the following error message: 

> "error in check_attributes(eventlog, attributes$attribute_name, attributes$attribute_values) : 
>   No case_id provided nor found"

I also tried with the dataset of patients from the eventdataR package with the following coding:
plot(end_activities(patients, "activity")) where I get the same error message as above

Thanks in advance for your help :)

**Comment by gertjanssenswillen** [comment]
Am I correct this issue is resolved using the latest version?
