### ISSUE TITLE
Plot for Processing Time with Level = Resource-Activity not consistent with other Levels

### ISSUE THREAD

**Issue by janmayer0105** [bupaverse/edeaR#22]
Hey guys, 

as mentioned in the title, I cannot find a proper way to plot the processing time for level "resource-activity".

Since the plots for processing time with level "resource" and "activity" can be plotted quite intuitively, the plot for level  "resource-activity" throws an error when it's plotted with the same attributes.

processing_time(
  patients,
  level = "resource",
  append = F,
  append_column = NULL,
  units = "mins",
  sort = T,
  work_schedule = NULL
) %>% plot()

This renders the following:
![image](https://user-images.githubusercontent.com/53741679/97988370-2b844a00-1ddd-11eb-9c86-81b229a5d841.png)

With having the same attributes but only change the attribute "level" to "resource-activity" gives back the following:

processing_time(
  patients,
  level = "resource-activity",
  append = F,
  append_column = NULL,
  units = "mins",
  sort = T,
  work_schedule = NULL
) %>% plot()

![image](https://user-images.githubusercontent.com/53741679/97988627-8b7af080-1ddd-11eb-9fd9-ade9ebe9991c.png)

The only way to escape this error (for me) is to set "append" to "TRUE", which will render a matrixplot of the table "patients" (which I think is not the goal).

processing_time(
  patients,
  level = "resource-activity",
  append = T,
  append_column = NULL,
  units = "mins",
  sort = T,
  work_schedule = NULL
) %>% plot()

![image](https://user-images.githubusercontent.com/53741679/97988944-152abe00-1dde-11eb-9766-ed1a92a83cc9.png)

Here my Sys.info() and R.Version
sysname           release           version          nodename                            machine 
"Windows"       "10 x64"     "build 19041"    "LAPTOP-2GC29OTT"          "x86-64"

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock 

It would be very helpful to get feedback from your end if there is any development planned or if it can be fixed in the source code.

Thanks again for your help!

Best,
Jan

**Comment by gertjanssenswillen** [comment]
Now solved in github. 

If you have any feedback on the default plots, feel free to share.
