### ISSUE TITLE
Filter precedence - package error

### ISSUE THREAD

**Issue by gervao** [bupaverse/edeaR#24]
the filter_precedence function has stopped working thanks

**Comment by gervao** [comment]
patients %>%
filter_precedence(antecedents = "Triage and Assessment",consequents = "Blood test",precedence_type = "directly_follows") %>%
traces

Error: names must not be null
Run rlang::last_error() to see where the error occurred

**Comment by gertjanssenswillen** [comment]
Which version of edeaR are you using? Can you try whether it works using the github-version?

**Comment by gervao** [comment]
I use the Github version

**Comment by gervao** [comment]
> rlang::last_error()
<error/tibble_error_names_must_be_non_null>
`names` must not be `NULL`.
Backtrace:
  1. `%>%`(...)
  9. tidyr::crossing(., sequence_pairs)
 10. purrr::map(cols, sorted_unique)
 11. tidyr:::.f(.x[[i]], ...)
 12. vctrs::vec_sort(vec_unique(x))
 13. vctrs::vec_order(x, direction = direction, na_value = na_value)
 14. vctrs:::order_proxy(...)
 17. base::unname(proxy)
 19. dplyr:::`names<-.rowwise_df`(`*tmp*`, value = NULL)
 20. dplyr:::rowwise_df(data, group_vars)
 22. dplyr:::as_tibble.rowwise_df(data)
 23. tibble::new_tibble(dplyr_vec_data(x), nrow = nrow(x))
Run `rlang::last_trace()` to see the full context.

**Comment by gervao** [comment]
> rlang::last_trace()
<error/tibble_error_names_must_be_non_null>
`names` must not be `NULL`.
Backtrace:
     x
  1. +-`%>%`(...)
  2. +-edeaR::filter_precedence(...)
  3. +-edeaR:::filter_precedence.eventlog(...)
  4. | \-`%>%`(...)
  5. +-dplyr::summarize(., n_fitting = sum(fits))
  6. +-dplyr::group_by(., trace)
  7. +-dplyr::mutate(., fits = str_detect(.trace, fixed(pattern)))
  8. \-tidyr::crossing(., sequence_pairs)
  9.   \-purrr::map(cols, sorted_unique)
 10.     \-tidyr:::.f(.x[[i]], ...)
 11.       \-vctrs::vec_sort(vec_unique(x))
 12.         \-vctrs::vec_order(x, direction = direction, na_value = na_value)
 13.           \-vctrs:::order_proxy(...)
 14.             +-vctrs:::map(...)
 15.             | \-base::lapply(.x, .f, ...)
 16.             \-base::unname(proxy)
 17.               +-base::`names<-`(`*tmp*`, value = NULL)
 18.               \-dplyr:::`names<-.rowwise_df`(`*tmp*`, value = NULL)
 19.                 \-dplyr:::rowwise_df(data, group_vars)
 20.                   +-tibble::as_tibble(data)
 21.                   \-dplyr:::as_tibble.rowwise_df(data)
 22.                     \-tibble::new_tibble(dplyr_vec_data(x), nrow = nrow(x))

**Comment by gertjanssenswillen** [comment]
Sorry for the delay

Could you show sessionInfo() when you get the error?

**Comment by gertjanssenswillen** [comment]
The error was due to a new R version, and should have been solved at this moment. (github version). 

New release of edeaR to follow in the coming weeks.
