### ISSUE TITLE
edeaR::resource_involvement with level="resource-activity" returns the expected output for level="resource"

### ISSUE THREAD

**Issue by rlmoore0** [bupaverse/edeaR#48]
This is for edeaR 0.9.1 (current cran version)

edeaR::resource_involvement(log = anEventLog, level = "resource-activity") matches the output of edeaR::resource_involvement(log = anEventLog, level = "resource")

It does not contain "resource-activity combinations" but only resources.  See the input event log contained in the file anEventLog.rda contained in the attached zip file and the output contained in the file results.rda in the attached zip file.

[anEventLog.zip](https://github.com/bupaverse/edeaR/files/10414683/anEventLog.zip)
[results.zip](https://github.com/bupaverse/edeaR/files/10414704/results.zip)

**Comment by gertjanssenswillen** [comment]
Issue is fixed on github.  New release expected to be on CRAN in coming days.
