### ISSUE TITLE
Implement filter_trace_id

### ISSUE THREAD

**Issue by hector-ps** [bupaverse/edeaR#7]
We are dealing with a preliminar study where we want to identify specific patterns on a set of cases. In order to actuate over the process, it is interesting to subset  those cases by specific traces. To achieve this the function `filter_activity_presence` can be used, passing the whole set of trace activities to the filter. If the traces are known (for instance, from the `trace_explorer` raw output) the id of the trace could be used instead. This feature is not implemented, and it seems that the trace explorer output does not map the whole set of cases to the traces (is this true?), which would enable the use of `dplyr::filter` in a custom function. 

Is there a way to perform this with the existing features of the (by the way, amazing!) packages? Is this traspassing the scope expected for the packages? 

Maybe I am missing something. I have work on the DataCamp course but I think this approach is not solved there. 

Thank you in advance for your effort.

**Comment by gertjanssenswillen** [comment]
Just for clarity: what you want to do is filter the log by providing a specific (set of) traces?
Also, can you elaborate on the remark related to trace explorer not mapping the whole set of cases?
Thx

**Comment by hector-ps** [comment]
Once the traces are known (using `traces` or `trace_explorer`) I would like to filter those cases that belong to an specific trace. I have achieved this splitting the trace name by commas, and using the obtained vector as input of `filter_activity_precedence`. Although this is not unconfortable anyway, I would like to know if there is a "package-oriented" way of make this filter.

For the additional part of your question:

I know `trace_explorer` is capable to return a raw dataset. I expected this output to be a table where any case where related to a trace. This would make easier to get those cases belonging to some traces. Howerver, the raw output does not include the whole set of cases identifiers.

Thank you in advance. This set of packages are enabling me to make complex analysis.

**Comment by hector-ps** [comment]
Dear Gert,

The use of both `cases()` and `traces()` **directly solves** what I was looking for, via `dplyr::filter`. I think I got stuck insisting on using the raw output of `trace_explorer` to relate each _case_ to a _trace_ instead of using those two functions.

``` {R}
# view over traces
traces(my_log)

# as example, focus on trace_id = 1
desired_cases <- cases(my_log) %>% dplyr::filter(trace_id == 1)

#get filtered log
filtered_log <- my_log %>% filter_case(cases = desired_cases[, attr(my_log,"case_id")])
```

Sorry for the inconvenience. If you see a cleaner way to achieve this output, I happily receive your feedback. 

Again, I would like to thank you for these powerful packages.

**Comment by gertjanssenswillen** [comment]
Working via cases and traces is the best way in my view, but indeed a bit cumbersome. 

With regards to trace explorer: the raw_data option I do not advise to use. It will just give you a random case for each trace in the trace explorer. 

**But**, you could give the trace explorer to eventlog, and then it will return an event log with all the traces that are in the trace explorer at that moment (which you can configure using coverage or n_traces). The code below, for example, returns an eventlog of all cases belonging to the 5 most frequent traces. 
`
eventlog(trace_explorer(data, n_traces = 5))
#5 
trace_explorer(data, n_traces = 5) %>% eventlog()
`
Of course, this doesn't help when the way you want to select traces is not easily done based on frequency. (This is a fairly recent feature, so it hasn't been widely known yet)

As a shorter way for the workaround with cases and traces, we could provide a filter_trace_id function, where you can insert a vector of trace ids. That would replace your last 2 steps with one. 
(I don't think it is useful to have a filter_trace() where you can insert a string with a trace, but we could provide that as well). 

I'm leaving this issue and change the name to implement at least the filter_trace_id

**Comment by gertjanssenswillen** [comment]
I have added a function `filter_trace` to directly filter on trace_ids
